apiVersion: v1
kind: Pod
metadata:
  labels:
    app: lns
  name: liv-readinses
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
        - cat
        - /usr/share/nginx/html/index.html
      initialDelaySeconds: 5
      periodSeconds: 5
  - name: con2
    image: tomcat:latest
    ports:
    - containerPort: 8080
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      tcpSocket:
         port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
